# 股票代码列表
# 格式：股票代码 - 股票名称

symbols:
  - code: "000001"
    name: "平安银行"
  - code: "000002"
    name: "万科A"
  - code: "600519"
    name: "贵州茅台"
  - code: "600036"
    name: "招商银行"
  - code: "000858"
    name: "五粮液"
  - code: "601318"
    name: "中国平安"
  - code: "600276"
    name: "恒瑞医药"
  - code: "300750"
    name: "宁德时代"
  - code: "601888"
    name: "中国中免"
  - code: "002594"
    name: "比亚迪"
