# 科创100成分股列表
# 格式：股票代码 - 股票名称
# 共 100 只股票
# 更新时间: 2026-01-14 18:14:23

symbols:
  - code: '688123'
    name: '聚辰股份'
  - code: '688313'
    name: '仕佳光子'
  - code: '688363'
    name: '华熙生物'
  - code: '688382'
    name: '益方生物'
  - code: '688563'
    name: '航材股份'
  - code: '688615'
    name: '合合信息'
  - code: '688660'
    name: '电气风电'
  - code: '688726'
    name: '拉普拉斯'
  - code: '688165'
    name: '埃夫特'
  - code: '688332'
    name: '中科蓝讯'
  - code: '688502'
    name: '茂莱光学'
  - code: '688561'
    name: '奇安信'
  - code: '688692'
    name: '达梦数据'
  - code: '688116'
    name: '天奈科技'
  - code: '688295'
    name: '中复神鹰'
  - code: '688522'
    name: '纳睿雷达'
  - code: '688584'
    name: '上海合晶'
  - code: '688631'
    name: '莱斯信息'
  - code: '688018'
    name: '乐鑫科技'
  - code: '688279'
    name: '峰�G科技'
  - code: '688385'
    name: '复旦微电'
  - code: '688301'
    name: '奕瑞科技'
  - code: '688629'
    name: '华丰科技'
  - code: '688676'
    name: '金盘科技'
  - code: '688709'
    name: '成都华微'
  - code: '688027'
    name: '国盾量子'
  - code: '688390'
    name: '固德威'
  - code: '688443'
    name: '智翔金泰'
  - code: '688063'
    name: '派能科技'
  - code: '688549'
    name: '中巨芯'
  - code: '688005'
    name: '容百科技'
  - code: '688433'
    name: '华曙高科'
  - code: '688032'
    name: '禾迈股份'
  - code: '688347'
    name: '华虹公司'
  - code: '688548'
    name: '广钢气体'
  - code: '688536'
    name: '思瑞浦'
  - code: '688336'
    name: '三生国健'
  - code: '688322'
    name: '奥比中光'
  - code: '688779'
    name: '长远锂科'
  - code: '688361'
    name: '中科飞测'
  - code: '688400'
    name: '凌云光'
  - code: '688052'
    name: '纳芯微'
  - code: '688612'
    name: '威迈斯'
  - code: '688582'
    name: '芯动联科'
  - code: '688498'
    name: '源杰科技'
  - code: '688484'
    name: '南芯科技'
  - code: '688352'
    name: '颀中科技'
  - code: '688343'
    name: '云天励飞'
  - code: '688235'
    name: '百济神州'
  - code: '688192'
    name: '迪哲医药'
  - code: '688146'
    name: '中船特气'
  - code: '688172'
    name: '燕东微'
  - code: '688141'
    name: '杰华特'
  - code: '688432'
    name: '有研硅'
  - code: '688772'
    name: '珠海冠宇'
  - code: '688147'
    name: '微导纳米'
  - code: '688001'
    name: '华兴源创'
  - code: '688002'
    name: '睿创微纳'
  - code: '688006'
    name: '杭可科技'
  - code: '688016'
    name: '心脉医疗'
  - code: '688017'
    name: '绿的谐波'
  - code: '688019'
    name: '安集科技'
  - code: '688029'
    name: '南微医学'
  - code: '688037'
    name: '芯源微'
  - code: '688050'
    name: '爱博医疗'
  - code: '688083'
    name: '中望软件'
  - code: '688088'
    name: '虹软科技'
  - code: '688097'
    name: '博众精工'
  - code: '688100'
    name: '威胜信息'
  - code: '688107'
    name: '安路科技'
  - code: '688110'
    name: '东芯股份'
  - code: '688139'
    name: '海尔生物'
  - code: '688153'
    name: '唯捷创芯'
  - code: '688161'
    name: '威高骨科'
  - code: '688166'
    name: '博瑞医药'
  - code: '688198'
    name: '佰仁医疗'
  - code: '688200'
    name: '华峰测控'
  - code: '688208'
    name: '道通科技'
  - code: '688248'
    name: '南网科技'
  - code: '688266'
    name: '泽�Z制药'
  - code: '688281'
    name: '华秦科技'
  - code: '688289'
    name: '圣湘生物'
  - code: '688318'
    name: '财富趋势'
  - code: '688326'
    name: '经纬恒润'
  - code: '688327'
    name: '云从科技'
  - code: '688331'
    name: '荣昌生物'
  - code: '688333'
    name: '铂力特'
  - code: '688387'
    name: '信科移动'
  - code: '688408'
    name: '中信博'
  - code: '688409'
    name: '富创精密'
  - code: '688425'
    name: '铁建重工'
  - code: '688439'
    name: '振华风光'
  - code: '688516'
    name: '奥特维'
  - code: '688520'
    name: '神州细胞'
  - code: '688567'
    name: '孚能科技'
  - code: '688568'
    name: '中科星图'
  - code: '688739'
    name: '成大生物'
  - code: '688778'
    name: '厦钨新能'
  - code: '688789'
    name: '宏华数科'
  - code: '688798'
    name: '艾为电子'
