# 沪深300成分股列表
# 格式：股票代码 - 股票名称
# 共 280 只股票
# 更新时间: 2026-01-14 18:14:21

symbols:
  - code: '002625'
    name: '光启技术'
  - code: '300476'
    name: '胜宏科技'
  - code: '300251'
    name: '光线传媒'
  - code: '002384'
    name: '东山精密'
  - code: '603893'
    name: '瑞芯微'
  - code: '300803'
    name: '指南针'
  - code: '601456'
    name: '国联民生'
  - code: '600522'
    name: '中天科技'
  - code: '601018'
    name: '宁波港'
  - code: '300866'
    name: '安克创新'
  - code: '600930'
    name: '华电新能'
  - code: '601298'
    name: '青岛港'
  - code: '002600'
    name: '领益智造'
  - code: '601077'
    name: '渝农商行'
  - code: '601825'
    name: '沪农商行'
  - code: '001391'
    name: '国货航'
  - code: '302132'
    name: '中航成飞'
  - code: '301236'
    name: '软通动力'
  - code: '688047'
    name: '龙芯中科'
  - code: '601058'
    name: '赛轮轮胎'
  - code: '688506'
    name: '百利天恒'
  - code: '601136'
    name: '首创证券'
  - code: '600066'
    name: '宇通客车'
  - code: '688472'
    name: '阿特斯'
  - code: '300394'
    name: '天孚通信'
  - code: '300502'
    name: '新易盛'
  - code: '600377'
    name: '宁沪高速'
  - code: '000630'
    name: '铜陵有色'
  - code: '601127'
    name: '赛力斯'
  - code: '002028'
    name: '思源电气'
  - code: '002463'
    name: '沪电股份'
  - code: '600482'
    name: '中国动力'
  - code: '688169'
    name: '石头科技'
  - code: '000975'
    name: '山金国际'
  - code: '002422'
    name: '科伦药业'
  - code: '600160'
    name: '巨化股份'
  - code: '600027'
    name: '华电国际'
  - code: '688009'
    name: '中国通号'
  - code: '688082'
    name: '盛美上海'
  - code: '603296'
    name: '华勤技术'
  - code: '000807'
    name: '云铝股份'
  - code: '600161'
    name: '天坛生物'
  - code: '600415'
    name: '小商品城'
  - code: '300442'
    name: '润泽科技'
  - code: '600026'
    name: '中远海能'
  - code: '300832'
    name: '新产业'
  - code: '300418'
    name: '昆仑万维'
  - code: '600489'
    name: '中金黄金'
  - code: '000999'
    name: '华润三九'
  - code: '300308'
    name: '中际旭创'
  - code: '600372'
    name: '中航机载'
  - code: '600938'
    name: '中国海油'
  - code: '688256'
    name: '寒武纪'
  - code: '301269'
    name: '华大九天'
  - code: '600515'
    name: '海南机场'
  - code: '688271'
    name: '联影医疗'
  - code: '600023'
    name: '浙能电力'
  - code: '601059'
    name: '信达证券'
  - code: '688041'
    name: '海光信息'
  - code: '601916'
    name: '浙商银行'
  - code: '601872'
    name: '招商轮船'
  - code: '000617'
    name: '中油资本'
  - code: '688223'
    name: '晶科能源'
  - code: '600875'
    name: '东方电气'
  - code: '601607'
    name: '上海医药'
  - code: '000983'
    name: '山西焦煤'
  - code: '600803'
    name: '新奥股份'
  - code: '600039'
    name: '四川路桥'
  - code: '688187'
    name: '时代电气'
  - code: '600674'
    name: '川投能源'
  - code: '601689'
    name: '拓普集团'
  - code: '688303'
    name: '大全能源'
  - code: '605117'
    name: '德业股份'
  - code: '600233'
    name: '圆通速递'
  - code: '000792'
    name: '盐湖股份'
  - code: '600219'
    name: '南山铝业'
  - code: '600188'
    name: '兖矿能源'
  - code: '002920'
    name: '德赛西威'
  - code: '002648'
    name: '卫星化学'
  - code: '300661'
    name: '圣邦股份'
  - code: '300979'
    name: '华利集团'
  - code: '000408'
    name: '藏格矿业'
  - code: '600089'
    name: '特变电工'
  - code: '603260'
    name: '合盛硅业'
  - code: '300999'
    name: '金龙鱼'
  - code: '300896'
    name: '爱美客'
  - code: '688981'
    name: '中芯国际'
  - code: '002466'
    name: '天齐锂业'
  - code: '601898'
    name: '中煤能源'
  - code: '000301'
    name: '东方盛虹'
  - code: '600905'
    name: '三峡能源'
  - code: '300782'
    name: '卓胜微'
  - code: '601728'
    name: '中国电信'
  - code: '300316'
    name: '晶盛机电'
  - code: '300759'
    name: '康龙化成'
  - code: '300760'
    name: '迈瑞医疗'
  - code: '601868'
    name: '中国能建'
  - code: '002459'
    name: '晶澳科技'
  - code: '300750'
    name: '宁德时代'
  - code: '002709'
    name: '天赐材料'
  - code: '605499'
    name: '东鹏饮料'
  - code: '688396'
    name: '华润微'
  - code: '688126'
    name: '沪硅产业'
  - code: '688111'
    name: '金山办公'
  - code: '601995'
    name: '中金公司'
  - code: '600426'
    name: '华鲁恒升'
  - code: '300274'
    name: '阳光电源'
  - code: '600600'
    name: '青岛啤酒'
  - code: '688012'
    name: '中微公司'
  - code: '603195'
    name: '公牛集团'
  - code: '002049'
    name: '紫光国微'
  - code: '600150'
    name: '中国船舶'
  - code: '603392'
    name: '万泰生物'
  - code: '600845'
    name: '宝信软件'
  - code: '600918'
    name: '中泰证券'
  - code: '688008'
    name: '澜起科技'
  - code: '000977'
    name: '浪潮信息'
  - code: '601816'
    name: '京沪高铁'
  - code: '603369'
    name: '今世缘'
  - code: '601100'
    name: '恒立液压'
  - code: '000708'
    name: '中信特钢'
  - code: '002371'
    name: '北方华创'
  - code: '003816'
    name: '中国广核'
  - code: '300014'
    name: '亿纬锂能'
  - code: '300628'
    name: '亿联网络'
  - code: '601658'
    name: '邮储银行'
  - code: '300347'
    name: '泰格医药'
  - code: '600183'
    name: '生益科技'
  - code: '600989'
    name: '宝丰能源'
  - code: '601236'
    name: '红塔证券'
  - code: '601698'
    name: '中国卫通'
  - code: '603501'
    name: '韦尔股份'
  - code: '002916'
    name: '深南电路'
  - code: '000596'
    name: '古井贡酒'
  - code: '002938'
    name: '鹏鼎控股'
  - code: '300413'
    name: '芒果超媒'
  - code: '300498'
    name: '温氏股份'
  - code: '601319'
    name: '中国人保'
  - code: '603019'
    name: '中科曙光'
  - code: '603986'
    name: '兆易创新'
  - code: '002179'
    name: '中航光电'
  - code: '000661'
    name: '长春高新'
  - code: '002001'
    name: '新和成'
  - code: '601138'
    name: '工业富联'
  - code: '002311'
    name: '海大集团'
  - code: '600760'
    name: '中航沈飞'
  - code: '601066'
    name: '中信建投'
  - code: '603259'
    name: '药明康德'
  - code: '601360'
    name: '三六零'
  - code: '600025'
    name: '华能水电'
  - code: '600346'
    name: '恒力股份'
  - code: '603288'
    name: '海天味业'
  - code: '601238'
    name: '广汽集团'
  - code: '601808'
    name: '中海油服'
  - code: '600176'
    name: '中国巨石'
  - code: '600438'
    name: '通威股份'
  - code: '600809'
    name: '山西汾酒'
  - code: '601838'
    name: '成都银行'
  - code: '601012'
    name: '隆基股份'
  - code: '002601'
    name: '龙蟒佰利'
  - code: '603799'
    name: '华友钴业'
  - code: '600011'
    name: '华能国际'
  - code: '002460'
    name: '赣锋锂业'
  - code: '601878'
    name: '浙商证券'
  - code: '300122'
    name: '智飞生物'
  - code: '300015'
    name: '爱尔眼科'
  - code: '002352'
    name: '顺丰控股'
  - code: '600436'
    name: '片仔癀'
  - code: '600919'
    name: '江苏银行'
  - code: '600926'
    name: '杭州银行'
  - code: '601229'
    name: '上海银行'
  - code: '601881'
    name: '中国银河'
  - code: '002714'
    name: '牧原股份'
  - code: '300033'
    name: '同花顺'
  - code: '601877'
    name: '正泰电器'
  - code: '000938'
    name: '紫光股份'
  - code: '002027'
    name: '分众传媒'
  - code: '600061'
    name: '国投安信'
  - code: '001979'
    name: '招商蛇口'
  - code: '601211'
    name: '国泰君安'
  - code: '601985'
    name: '中国核电'
  - code: '002736'
    name: '国信证券'
  - code: '300059'
    name: '东方财富'
  - code: '600958'
    name: '东方证券'
  - code: '601021'
    name: '春秋航空'
  - code: '601788'
    name: '光大证券'
  - code: '601919'
    name: '中国远洋'
  - code: '000166'
    name: '申万宏源'
  - code: '600570'
    name: '恒生电子'
  - code: '300124'
    name: '汇川技术'
  - code: '601225'
    name: '陕西煤业'
  - code: '002252'
    name: '上海莱士'
  - code: '002475'
    name: '立讯精密'
  - code: '600018'
    name: '上港集团'
  - code: '002230'
    name: '科大讯飞'
  - code: '000333'
    name: '美的集团'
  - code: '000963'
    name: '华东医药'
  - code: '603993'
    name: '洛阳钼业'
  - code: '002236'
    name: '大华股份'
  - code: '600886'
    name: '国投电力'
  - code: '601800'
    name: '中国交建'
  - code: '000725'
    name: '京东方A'
  - code: '002241'
    name: '歌尔声学'
  - code: '601336'
    name: '新华保险'
  - code: '601633'
    name: '长城汽车'
  - code: '601669'
    name: '中国水电'
  - code: '601901'
    name: '方正证券'
  - code: '002594'
    name: '比亚迪'
  - code: '601377'
    name: '兴业证券'
  - code: '000776'
    name: '广发证券'
  - code: '002415'
    name: '海康威视'
  - code: '600115'
    name: '东方航空'
  - code: '600276'
    name: '恒瑞医药'
  - code: '600406'
    name: '国电南瑞'
  - code: '600887'
    name: '伊利股份'
  - code: '600893'
    name: '航空动力'
  - code: '601818'
    name: '光大银行'
  - code: '601288'
    name: '农业银行'
  - code: '002304'
    name: '洋河股份'
  - code: '600999'
    name: '招商证券'
  - code: '601688'
    name: '华泰证券'
  - code: '601888'
    name: '中国国旅'
  - code: '601618'
    name: '中国中冶'
  - code: '601668'
    name: '中国建筑'
  - code: '601766'
    name: '中国南车'
  - code: '000100'
    name: 'TCL集团'
  - code: '600588'
    name: '用友软件'
  - code: '601186'
    name: '中国铁建'
  - code: '601899'
    name: '紫金矿业'
  - code: '601390'
    name: '中国中铁'
  - code: '601601'
    name: '中国太保'
  - code: '601939'
    name: '建设银行'
  - code: '000338'
    name: '潍柴动力'
  - code: '000895'
    name: '双汇发展'
  - code: '002142'
    name: '宁波银行'
  - code: '600111'
    name: '包钢稀土'
  - code: '601009'
    name: '南京银行'
  - code: '601169'
    name: '北京银行'
  - code: '601857'
    name: '中国石油'
  - code: '601088'
    name: '中国神华'
  - code: '000876'
    name: '新希望'
  - code: '601328'
    name: '交通银行'
  - code: '601998'
    name: '中信银行'
  - code: '601600'
    name: '中国铝业'
  - code: '601318'
    name: '中国平安'
  - code: '601166'
    name: '兴业银行'
  - code: '601628'
    name: '中国人寿'
  - code: '600547'
    name: '山东黄金'
  - code: '601111'
    name: '中国国航'
  - code: '600048'
    name: '保利地产'
  - code: '601398'
    name: '工商银行'
  - code: '601006'
    name: '大秦铁路'
  - code: '601988'
    name: '中国银行'
  - code: '000768'
    name: '西飞国际'
  - code: '000538'
    name: '云南白药'
  - code: '600690'
    name: '青岛海尔'
  - code: '600660'
    name: '福耀玻璃'
  - code: '600585'
    name: '海螺水泥'
  - code: '600519'
    name: '贵州茅台'
  - code: '600362'
    name: '江西铜业'
  - code: '000858'
    name: '五粮液'
  - code: '000625'
    name: '长安汽车'
  - code: '000651'
    name: '格力电器'
  - code: '000568'
    name: '泸州老窖'
  - code: '000425'
    name: '徐工科技'
  - code: '000157'
    name: '中联重科'
  - code: '000063'
    name: '中兴通讯'
  - code: '000001'
    name: '深发展A'
  - code: '600009'
    name: '上海机场'
  - code: '600010'
    name: '包钢股份'
  - code: '600015'
    name: '华夏银行'
  - code: '600016'
    name: '民生银行'
  - code: '600019'
    name: '宝钢股份'
  - code: '600028'
    name: '中国石化'
  - code: '600029'
    name: '南方航空'
  - code: '600030'
    name: '中信证券'
  - code: '600031'
    name: '三一重工'
  - code: '600036'
    name: '招商银行'
  - code: '600050'
    name: '中国联通'
  - code: '000002'
    name: '万科A'
