# 中证500成分股列表
# 格式：股票代码 - 股票名称
# 共 425 只股票
# 更新时间: 2026-01-14 18:14:22

symbols:
  - code: '688037'
    name: '芯源微'
  - code: '300972'
    name: '万辰集团'
  - code: '002157'
    name: '正邦科技'
  - code: '603806'
    name: '福斯特'
  - code: '603049'
    name: '中策橡胶'
  - code: '002126'
    name: '银轮股份'
  - code: '601799'
    name: '星宇股份'
  - code: '688166'
    name: '博瑞医药'
  - code: '301200'
    name: '大族数控'
  - code: '002402'
    name: '和而泰'
  - code: '300432'
    name: '富临精工'
  - code: '603766'
    name: '隆鑫通用'
  - code: '601699'
    name: '潞安环能'
  - code: '601567'
    name: '三星医疗'
  - code: '002131'
    name: '利欧股份'
  - code: '002265'
    name: '建设工业'
  - code: '300718'
    name: '长盛轴承'
  - code: '002128'
    name: '电投能源'
  - code: '688018'
    name: '乐鑫科技'
  - code: '600642'
    name: '申能股份'
  - code: '600332'
    name: '白云山'
  - code: '003021'
    name: '兆威机电'
  - code: '000088'
    name: '盐田港'
  - code: '002271'
    name: '东方雨虹'
  - code: '300100'
    name: '双林股份'
  - code: '002583'
    name: '海能达'
  - code: '301611'
    name: '珂玛科技'
  - code: '002335'
    name: '科华数据'
  - code: '000657'
    name: '中钨高新'
  - code: '002032'
    name: '苏泊尔'
  - code: '603699'
    name: '纽威股份'
  - code: '300570'
    name: '太辰光'
  - code: '603444'
    name: '吉比特'
  - code: '600601'
    name: '方正科技'
  - code: '601865'
    name: '福莱特'
  - code: '001221'
    name: '悍高集团'
  - code: '688019'
    name: '安集科技'
  - code: '600602'
    name: '云赛智联'
  - code: '603833'
    name: '欧派家居'
  - code: '600967'
    name: '内蒙一机'
  - code: '688599'
    name: '天合光能'
  - code: '688347'
    name: '华虹公司'
  - code: '688266'
    name: '泽�Z制药'
  - code: '688629'
    name: '华丰科技'
  - code: '688192'
    name: '迪哲医药'
  - code: '300627'
    name: '华测导航'
  - code: '000933'
    name: '神火股份'
  - code: '601921'
    name: '浙版传媒'
  - code: '300450'
    name: '先导智能'
  - code: '000951'
    name: '中国重汽'
  - code: '600363'
    name: '联创光电'
  - code: '002837'
    name: '英维克'
  - code: '000582'
    name: '北部湾港'
  - code: '603659'
    name: '璞泰来'
  - code: '300623'
    name: '捷捷微电'
  - code: '600171'
    name: '上海贝岭'
  - code: '603565'
    name: '中谷物流'
  - code: '601333'
    name: '广深铁路'
  - code: '002007'
    name: '华兰生物'
  - code: '300458'
    name: '全志科技'
  - code: '300115'
    name: '长盈精密'
  - code: '002130'
    name: '沃尔核材'
  - code: '300757'
    name: '罗博特科'
  - code: '001696'
    name: '宗申动力'
  - code: '002312'
    name: '川发龙蟒'
  - code: '300679'
    name: '电连技术'
  - code: '600985'
    name: '淮北矿业'
  - code: '002773'
    name: '康弘药业'
  - code: '002851'
    name: '麦格米特'
  - code: '300346'
    name: '南大光电'
  - code: '300857'
    name: '协创数据'
  - code: '002461'
    name: '珠江啤酒'
  - code: '600562'
    name: '国睿科技'
  - code: '301536'
    name: '星宸科技'
  - code: '688183'
    name: '生益电子'
  - code: '300454'
    name: '深信服'
  - code: '001213'
    name: '中铁特货'
  - code: '688676'
    name: '金盘科技'
  - code: '688235'
    name: '百济神州'
  - code: '688702'
    name: '盛科通信'
  - code: '688728'
    name: '格科微'
  - code: '688100'
    name: '威胜信息'
  - code: '688027'
    name: '国盾量子'
  - code: '300140'
    name: '节能环境'
  - code: '300751'
    name: '迈为股份'
  - code: '300919'
    name: '中伟股份'
  - code: '600487'
    name: '亨通光电'
  - code: '300142'
    name: '沃森生物'
  - code: '301308'
    name: '江波龙'
  - code: '300223'
    name: '北京君正'
  - code: '300339'
    name: '润和软件'
  - code: '688578'
    name: '艾力斯'
  - code: '688563'
    name: '航材股份'
  - code: '688469'
    name: '芯联集成'
  - code: '603899'
    name: '晨光股份'
  - code: '301301'
    name: '川宁生物'
  - code: '600007'
    name: '中国国贸'
  - code: '600312'
    name: '平高电气'
  - code: '600295'
    name: '鄂尔多斯'
  - code: '600132'
    name: '重庆啤酒'
  - code: '300957'
    name: '贝泰妮'
  - code: '600606'
    name: '绿地控股'
  - code: '301498'
    name: '乖宝宠物'
  - code: '600720'
    name: '中交设计'
  - code: '603129'
    name: '春风动力'
  - code: '603605'
    name: '珀莱雅'
  - code: '603341'
    name: '龙旗科技'
  - code: '601001'
    name: '晋控煤业'
  - code: '300496'
    name: '中科创达'
  - code: '601918'
    name: '新集能源'
  - code: '688363'
    name: '华熙生物'
  - code: '688361'
    name: '中科飞测'
  - code: '688278'
    name: '特宝生物'
  - code: '600483'
    name: '福能股份'
  - code: '601399'
    name: '国机重装'
  - code: '603179'
    name: '新泉股份'
  - code: '603087'
    name: '甘李药业'
  - code: '601019'
    name: '山东出版'
  - code: '600816'
    name: '建元信托'
  - code: '601965'
    name: '中国汽研'
  - code: '603290'
    name: '斯达半导'
  - code: '601615'
    name: '明阳智能'
  - code: '301358'
    name: '湖南裕能'
  - code: '600763'
    name: '通策医疗'
  - code: '601212'
    name: '白银有色'
  - code: '600754'
    name: '锦江酒店'
  - code: '688065'
    name: '凯赛生物'
  - code: '688525'
    name: '佰维存储'
  - code: '688475'
    name: '萤石网络'
  - code: '688213'
    name: '思特威'
  - code: '600578'
    name: '京能电力'
  - code: '603298'
    name: '杭叉集团'
  - code: '603345'
    name: '安井食品'
  - code: '603486'
    name: '科沃斯'
  - code: '603728'
    name: '鸣志电器'
  - code: '603979'
    name: '金诚信'
  - code: '688017'
    name: '绿的谐波'
  - code: '688172'
    name: '燕东微'
  - code: '688561'
    name: '奇安信'
  - code: '688617'
    name: '惠泰医疗'
  - code: '688777'
    name: '中控技术'
  - code: '002607'
    name: '中公教育'
  - code: '002756'
    name: '永兴材料'
  - code: '003022'
    name: '联泓新科'
  - code: '300601'
    name: '康泰生物'
  - code: '600004'
    name: '白云机场'
  - code: '600583'
    name: '海油工程'
  - code: '600884'
    name: '杉杉股份'
  - code: '600977'
    name: '中国电影'
  - code: '601216'
    name: '君正集团'
  - code: '603606'
    name: '东方电缆'
  - code: '688114'
    name: '华大智造'
  - code: '688122'
    name: '西部超导'
  - code: '688180'
    name: '君实生物'
  - code: '688297'
    name: '中无人机'
  - code: '688349'
    name: '三一重能'
  - code: '688375'
    name: '国博电子'
  - code: '688387'
    name: '信科移动'
  - code: '688120'
    name: '华海清科'
  - code: '688425'
    name: '铁建重工'
  - code: '688778'
    name: '厦钨新能'
  - code: '688520'
    name: '神州细胞'
  - code: '688295'
    name: '中复神鹰'
  - code: '688281'
    name: '华秦科技'
  - code: '688248'
    name: '南网科技'
  - code: '688234'
    name: '天岳先进'
  - code: '688220'
    name: '翱捷科技'
  - code: '688052'
    name: '纳芯微'
  - code: '603529'
    name: '爱玛科技'
  - code: '603338'
    name: '浙江鼎力'
  - code: '601966'
    name: '玲珑轮胎'
  - code: '600995'
    name: '南网储能'
  - code: '300748'
    name: '金力永磁'
  - code: '300529'
    name: '健帆生物'
  - code: '300487'
    name: '蓝晓科技'
  - code: '300395'
    name: '菲利华'
  - code: '002608'
    name: '江苏国信'
  - code: '002432'
    name: '九安医疗'
  - code: '002008'
    name: '大族激光'
  - code: '000958'
    name: '电投产融'
  - code: '000893'
    name: '亚钾国际'
  - code: '000423'
    name: '东阿阿胶'
  - code: '603596'
    name: '伯特利'
  - code: '601233'
    name: '桐昆股份'
  - code: '300604'
    name: '长川科技'
  - code: '002340'
    name: '格林美'
  - code: '600655'
    name: '豫园股份'
  - code: '600873'
    name: '梅花生物'
  - code: '605358'
    name: '立昂微'
  - code: '688772'
    name: '珠海冠宇'
  - code: '002025'
    name: '航天电器'
  - code: '000703'
    name: '恒逸石化'
  - code: '300003'
    name: '乐普医疗'
  - code: '002080'
    name: '中材科技'
  - code: '002738'
    name: '中矿资源'
  - code: '603816'
    name: '顾家家居'
  - code: '603688'
    name: '石英股份'
  - code: '600378'
    name: '昊华科技'
  - code: '000683'
    name: '远兴能源'
  - code: '002850'
    name: '科达利'
  - code: '300373'
    name: '扬杰科技'
  - code: '601666'
    name: '平煤股份'
  - code: '000155'
    name: '川能动力'
  - code: '688385'
    name: '复旦微电'
  - code: '000591'
    name: '太阳能'
  - code: '688538'
    name: '和辉光电'
  - code: '603737'
    name: '三棵树'
  - code: '600032'
    name: '浙江新能'
  - code: '600352'
    name: '浙江龙盛'
  - code: '603160'
    name: '汇顶科技'
  - code: '600143'
    name: '金发科技'
  - code: '601108'
    name: '财通证券'
  - code: '000783'
    name: '长江证券'
  - code: '600499'
    name: '科达制造'
  - code: '603939'
    name: '益丰药房'
  - code: '300676'
    name: '华大基因'
  - code: '300677'
    name: '英科医疗'
  - code: '300390'
    name: '天华超净'
  - code: '600927'
    name: '永安期货'
  - code: '300144'
    name: '宋城演艺'
  - code: '688819'
    name: '天能股份'
  - code: '601990'
    name: '南京证券'
  - code: '300073'
    name: '当升科技'
  - code: '000785'
    name: '居然之家'
  - code: '603233'
    name: '大参林'
  - code: '000987'
    name: '越秀金控'
  - code: '002673'
    name: '西部证券'
  - code: '601665'
    name: '齐鲁银行'
  - code: '002508'
    name: '老板电器'
  - code: '600906'
    name: '财达证券'
  - code: '002739'
    name: '万达电影'
  - code: '600157'
    name: '永泰能源'
  - code: '002430'
    name: '杭氧股份'
  - code: '600118'
    name: '中国卫星'
  - code: '600299'
    name: '安迪苏'
  - code: '601555'
    name: '东吴证券'
  - code: '002939'
    name: '长城证券'
  - code: '002153'
    name: '石基信息'
  - code: '300724'
    name: '捷佳伟创'
  - code: '300136'
    name: '信维通信'
  - code: '600521'
    name: '华海药业'
  - code: '002945'
    name: '华林证券'
  - code: '601156'
    name: '东航物流'
  - code: '002409'
    name: '雅克科技'
  - code: '600298'
    name: '安琪酵母'
  - code: '688188'
    name: '柏楚电子'
  - code: '000728'
    name: '国元证券'
  - code: '002532'
    name: '天山铝业'
  - code: '002065'
    name: '东华软件'
  - code: '300037'
    name: '新宙邦'
  - code: '600208'
    name: '新湖中宝'
  - code: '600095'
    name: '湘财股份'
  - code: '300383'
    name: '光环新网'
  - code: '601577'
    name: '长沙银行'
  - code: '601198'
    name: '东兴证券'
  - code: '600998'
    name: '九州通'
  - code: '600988'
    name: '赤峰黄金'
  - code: '600663'
    name: '陆家嘴'
  - code: '600637'
    name: '东方明珠'
  - code: '600536'
    name: '中国软件'
  - code: '600498'
    name: '烽火通信'
  - code: '600390'
    name: '五矿资本'
  - code: '600369'
    name: '西南证券'
  - code: '003035'
    name: '南网能源'
  - code: '002958'
    name: '青农商行'
  - code: '002439'
    name: '启明星辰'
  - code: '600177'
    name: '雅戈尔'
  - code: '600764'
    name: '中国海防'
  - code: '300146'
    name: '汤臣倍健'
  - code: '600871'
    name: '石化油服'
  - code: '603589'
    name: '口子窖'
  - code: '600517'
    name: '国网英大'
  - code: '600968'
    name: '海油发展'
  - code: '300699'
    name: '光威复材'
  - code: '600038'
    name: '中直股份'
  - code: '002966'
    name: '苏州银行'
  - code: '600131'
    name: '国网信通'
  - code: '601997'
    name: '贵阳银行'
  - code: '600170'
    name: '上海建工'
  - code: '600398'
    name: '海澜之家'
  - code: '002299'
    name: '圣农发展'
  - code: '688099'
    name: '晶晨股份'
  - code: '600516'
    name: '方大炭素'
  - code: '000709'
    name: '河钢股份'
  - code: '688002'
    name: '睿创微纳'
  - code: '002683'
    name: '宏大爆破'
  - code: '600546'
    name: '山煤国际'
  - code: '603927'
    name: '中科软'
  - code: '300017'
    name: '网宿科技'
  - code: '002138'
    name: '顺络电子'
  - code: '600535'
    name: '天士力'
  - code: '002156'
    name: '通富微电'
  - code: '603786'
    name: '科博达'
  - code: '300474'
    name: '景嘉微'
  - code: '600153'
    name: '建发股份'
  - code: '600566'
    name: '济川药业'
  - code: '300024'
    name: '机器人'
  - code: '002294'
    name: '信立泰'
  - code: '002185'
    name: '华天科技'
  - code: '002595'
    name: '豪迈科技'
  - code: '000629'
    name: '攀钢钒钛'
  - code: '000739'
    name: '普洛药业'
  - code: '000898'
    name: '鞍钢股份'
  - code: '002429'
    name: '兆驰股份'
  - code: '300070'
    name: '碧水源'
  - code: '000050'
    name: '深天马A'
  - code: '000825'
    name: '太钢不锈'
  - code: '000967'
    name: '盈峰环境'
  - code: '002203'
    name: '海亮股份'
  - code: '002423'
    name: '中粮资本'
  - code: '300285'
    name: '国瓷材料'
  - code: '600339'
    name: '中油工程'
  - code: '600704'
    name: '物产中大'
  - code: '601228'
    name: '广州港'
  - code: '601598'
    name: '中国外运'
  - code: '603379'
    name: '三美股份'
  - code: '603858'
    name: '步长制药'
  - code: '002797'
    name: '第一创业'
  - code: '002926'
    name: '华西证券'
  - code: '600486'
    name: '扬农化工'
  - code: '600497'
    name: '驰宏锌锗'
  - code: '600549'
    name: '厦门钨业'
  - code: '600707'
    name: '彩虹股份'
  - code: '600739'
    name: '辽宁成大'
  - code: '600909'
    name: '华安证券'
  - code: '601118'
    name: '海南橡胶'
  - code: '601139'
    name: '深圳燃气'
  - code: '601611'
    name: '中国核建'
  - code: '000932'
    name: '华菱钢铁'
  - code: '601106'
    name: '中国一重'
  - code: '600959'
    name: '江苏有线'
  - code: '000060'
    name: '中金岭南'
  - code: '000623'
    name: '吉林敖东'
  - code: '600820'
    name: '隧道股份'
  - code: '600901'
    name: '江苏租赁'
  - code: '000559'
    name: '万向钱潮'
  - code: '600008'
    name: '首创股份'
  - code: '600699'
    name: '均胜电子'
  - code: '002372'
    name: '伟星新材'
  - code: '601958'
    name: '金钼股份'
  - code: '603650'
    name: '彤程新材'
  - code: '601866'
    name: '中远海发'
  - code: '002385'
    name: '大北农'
  - code: '002500'
    name: '山西证券'
  - code: '000537'
    name: '广宇发展'
  - code: '000750'
    name: '国海证券'
  - code: '002465'
    name: '海格通信'
  - code: '000738'
    name: '航发控制'
  - code: '603885'
    name: '吉祥航空'
  - code: '600021'
    name: '上海电力'
  - code: '002831'
    name: '裕同科技'
  - code: '601179'
    name: '中国西电'
  - code: '601098'
    name: '中南传媒'
  - code: '600528'
    name: '中铁工业'
  - code: '601608'
    name: '中信重工'
  - code: '600885'
    name: '宏发股份'
  - code: '603225'
    name: '新凤鸣'
  - code: '600060'
    name: '海信电器'
  - code: '000009'
    name: '中国宝安'
  - code: '002152'
    name: '广电运通'
  - code: '002195'
    name: '二三四五'
  - code: '000887'
    name: '中鼎股份'
  - code: '600737'
    name: '中粮糖业'
  - code: '601128'
    name: '常熟银行'
  - code: '600598'
    name: '北大荒'
  - code: '000027'
    name: '深圳能源'
  - code: '000039'
    name: '中集集团'
  - code: '000729'
    name: '燕京啤酒'
  - code: '300058'
    name: '蓝色光标'
  - code: '600126'
    name: '杭钢股份'
  - code: '600582'
    name: '天地科技'
  - code: '601928'
    name: '凤凰传媒'
  - code: '603000'
    name: '人民网'
  - code: '603228'
    name: '景旺电子'
  - code: '002670'
    name: '国盛金控'
  - code: '600863'
    name: '内蒙华电'
  - code: '601016'
    name: '节能风电'
  - code: '000960'
    name: '锡业股份'
  - code: '600862'
    name: '中航高科'
  - code: '000400'
    name: '许继电气'
  - code: '000598'
    name: '兴蓉环境'
  - code: '000878'
    name: '云南铜业'
  - code: '000937'
    name: '冀中能源'
  - code: '002353'
    name: '杰瑞股份'
  - code: '300001'
    name: '特锐德'
  - code: '600166'
    name: '福田汽车'
  - code: '600282'
    name: '南钢股份'
  - code: '600316'
    name: '洪都航空'
  - code: '600348'
    name: '阳泉煤业'
  - code: '601168'
    name: '西部矿业'
  - code: '603568'
    name: '伟明环保'
  - code: '600808'
    name: '马钢股份'
  - code: '600062'
    name: '华润双鹤'
  - code: '000519'
    name: '江南红箭'
  - code: '002155'
    name: '辰州矿业'
  - code: '002244'
    name: '滨江集团'
  - code: '600970'
    name: '中材国际'
  - code: '601717'
    name: '郑煤机'
  - code: '600392'
    name: '盛和资源'
  - code: '002266'
    name: '浙富股份'
  - code: '002273'
    name: '水晶光电'
  - code: '601000'
    name: '唐山港'
  - code: '000021'
    name: '长城开发'
  - code: '603077'
    name: '和邦股份'
  - code: '600380'
    name: '健康元'
  - code: '600879'
    name: '航天电子'
  - code: '601880'
    name: '大连港'
  - code: '002223'
    name: '鱼跃医疗'
  - code: '002444'
    name: '巨星科技'
  - code: '600435'
    name: '中兵光电'
  - code: '002281'
    name: '光迅科技'
  - code: '000513'
    name: '丽珠集团'
  - code: '600511'
    name: '国药股份'
  - code: '002078'
    name: '太阳纸业'
  - code: '600329'
    name: '中新药业'
  - code: '600141'
    name: '兴发集团'
  - code: '600765'
    name: '力源液压'
  - code: '600801'
    name: '华新水泥'
  - code: '600673'
    name: '东阳光铝'
  - code: '000997'
    name: '新大陆'
  - code: '002056'
    name: '横店东磁'
  - code: '000563'
    name: '陕国投A'
  - code: '000830'
    name: '鲁西化工'
  - code: '600563'
    name: '法拉电子'
  - code: '600580'
    name: '卧龙电气'
